# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary
  - C:\Users\appveyor\AppData\Roaming\local\bin
  - "%LOCALAPPDATA%\\Programs\\stack"

# Adapt as necessary starting from here

environment:
  PYTHON3: C:\Python35\Scripts
  PYTHON3ALT: C:\python35\Scripts

build_script:
  - travis-tool.sh install_deps

test_script:
  - cmd: set PATH=%PYTHON3%;%PYTHON3ALT%;C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%;
# - cmd: set PATH=C:\Users\appveyor\AppData\Roaming\local\bin;%PATH%;
  - cinst ledger
  - cinst haskell-stack
  - cmd: stack --silent install --resolver=lts hledger-lib-1.9 hledger-1.9
  - cmd: "%PYTHON3%\\pip --quiet install beancount"
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - cmd: ledger --version
  - cmd: hledger --version
  - cmd: bean-report --version

on_success:
  - Rscript -e "covr::codecov()"

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
