language: r
r:
    - release
    - devel 
os:
    - linux
sudo: enabled
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ bionic main universe"
    - sudo apt-get -qq update
    ## Ledger
    - sudo apt-get install -y ledger
    ## HLedger
    - sudo apt-get install -y hledger
    ## Beancount
    - sudo apt-get install -y python3 python3-pip
    - sudo -H pip3 install beancount
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
    - r-lib/covr
after_success:
    - Rscript -e 'covr::codecov()'
