language: r
r:
    - release
    - devel 
os:
    - linux
sudo: enabled
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
before_install:
    ## Ledger
    - git clone git://github.com/ledger/ledger.git
    - sudo ledger/acprep dependencies
    - sudo ledger/acprep update
    ## HLedger
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - sudo stack install --resolver=lts hledger-lib-1.9 hledger-1.9
    ## Beancount
    # Need to figure out how to install python 3.5+
    - sudo apt-get install -y python3-pip
    - sudo -H pip3 install beancount
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
    - r-lib/covr
after_success:
    - Rscript -e 'covr::codecov()'
