language: r
r:
    - release
    - devel 
os:
    - linux
sudo: enabled
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
before_install:
    - sudo apt-get install -y python3-pip haskell-stack
    - sudo pip3 install beancount
    - sudo stack upgrade
    - sudo stack install --resolver=lts hledger-lib-1.9 hledger-1.9
    - git clone git://github.com/ledger/ledger.git
    - sudo ledger/acprep dependencies
    - sudo ledger/acprep update
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
    - r-lib/covr
after_success:
    - Rscript -e 'covr::codecov()'
