language: r
r:
    - release
    - devel 
os:
    - linux
sudo: enabled
latex: false
warnings_are_errors: true
cran: https://cran.rstudio.com
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
    - sudo apt-get -qq update
    ## Ledger
    - sudo apt-get install -y ledger
    ## HLedger
    # - sudo apt-get install -y haskell-stack
    # - sudo stack upgrade
    - mkdir -p ~/.local/bin ~/.stack
    - export PATH=$HOME/.local/bin:$PATH
    - wget -qO- https://get.haskellstack.org/ | sh -s - -f
    - sudo stack install --resolver=lts hledger-lib-1.9 hledger-1.9
    ## Beancount
    - sudo apt-get install -y python3 python3-pip
    - sudo -H pip3 install beancount
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
    - r-lib/covr
after_success:
    - Rscript -e 'covr::codecov()'
